########
# Diff #
########
    diffi = diff -C --cached
    dif = diff -C
    di = diff -C
    dii = diff -C --cached
    diffstat = diff -C --stat
    ds = diff -C --stat
    dsi = diff -C --stat --cached
    diffw = diff -C --ignore-all-space
    diffwi = diff -C --ignore-all-space --cached
    diffiw = diff -C --ignore-all-space --cached
    dw = diff -C --ignore-all-space
    dwi = diff -C --ignore-all-space --cached
    dsw = diff -C --stat --ignore-all-space
    dws = diff -C --stat --ignore-all-space
    dswi = diff -C --stat --ignore-all-space --cached
    dsiw = diff -C --stat --ignore-all-space --cached

