CT=                     \
ct010-aliases.sh        \
ct020-checkout.sh       \
ct030-branch.sh         \
ct040-commit.sh         \
ct050-fetch.sh          \
ct051-fetch-frc.sh      \
ct060-votes.sh

CT_EXAMPLE=     \
ct0-base.sh
