CT=                     \
ct1-aliases.sh          \
ct2-checkout.sh         \
ct3-branch.sh           \
ct4-commit.sh           \
ct5-fetch.sh            \
ct51-fetch-frc.sh       \
ct6-votes.sh

CT_EXAMPLE=     \
ct0-base.sh
